#!/usr/bin/env bash

ssh ubuntu@44.203.131.96 -i ~/.ssh/school
mkdir -p ~/.ssh && touch ~/.ssh/authorized_keys
chmod 700 ~/.ssh && chmod 600 ~/.ssh/authorized_keys
echo ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQC68pLh7ORMBWR5DdNWk0hmb7n2sOJbgKVnij3bjOVA7NTDfdF2FDjnvFewAqTxNpqAiwF9s4u7GS06/UNrFlB/hR+GYqVrSLdiwHqMzJ/Wzq6sJqvNaU/zQth7NkEFwqXY+3/lGZv6OfCh9wv9tADe/kiRF4GuGpDqhHl/w5OI/w==>> ~/.ssh/authorized_keys
